### ISSUE TITLE
Ceedling doesn't include rakefile.rb any more

### ISSUE THREAD

**Issue by andrewwade** [SublimeText/Ceedling#3]
All commands using `rake <args>` no longer work with latest Ceedling releases. Needs updated to use `ceedling <args>` style commands.

**Comment by FichteFoll** [comment]
I'm not sure whether this repo is still maintained and I have no idea what it is about, but if you submit a Pull Request with your suggested changes, I can merge it.

**Comment by pajacobson** [comment]
Resolved by PR #7
