### ISSUE TITLE
SublimeText 3 support

### ISSUE THREAD

**Issue by bdun** [SublimeText/Ceedling#4]
I just saw this plugin, and would be great to have on sublime text3.  Is there any chance this will be supported - or is it already supported and I'm missing something for installing? It doesn't come up on the list when trying to install, but can see it in my sublime text 2.

**Comment by bdun** [comment]
Just noticed there is a PR already here for this. Could that please get merged in?

**Comment by pajacobson** [comment]
Resolved by PR #7
